### ISSUE TITLE
Establish an acronym definition for MULE in which the M stands for Mountain

### ISSUE THREAD

**Issue by joshhting** [MountainRange/MULE#1]

**Comment by jgkamat** [comment]
Mountain Under Le Earth?
I'm no good at these acronym things

**Comment by joshhting** [comment]
I like it

**Comment by joshhting** [comment]
Also something like Mountains of Unused Lambda Expressions

And then we could just leave actual unused lambda expressions in our code :P

**Comment by jgkamat** [comment]
:+1:  yessssss
