### ISSUE TITLE
Restructure code following the aftermath of the demo screwup

### ISSUE THREAD

**Issue by joshhting** [MountainRange/MULE#12]
- Remove switch statements
- Have player count option on previous scene rather than the player config scene
- Remove switch statements

**Comment by strburst** [comment]
Is it safe to close this issue?

**Comment by joshhting** [comment]
Are the switch statements gone?

**Comment by jgkamat** [comment]
@rmkeezer close if you removed the switch statment, otherwise open n more issues where n is the number of case statements.

**Comment by joshhting** [comment]
We have officially switched to being switch-free
