### ISSUE TITLE
Determine style guides

### ISSUE THREAD

**Issue by jgkamat** [MountainRange/MULE#2]
We need to decide on what style to use, being consistent is more important than using your favorite things! Comment on what you like, and we can just pick majority.
I'm going to say we use editorconfig to keep things clean, so download the plugin! :smile: 
- Tabs/spaces/custom scheme
- Max Line Length
- Filesystem layout?

Add your own...
@MountainRange/developers

**Comment by jgkamat** [comment]
My Vote

Tabs
120 Line Max Length
Standard java/gradle filesystem layout

**Comment by joshhting** [comment]
I second Jay's vote in its entirety

**Comment by strburst** [comment]
I would prefer using 4 spaces, and maybe keeping lines to 79/80 characters, but that's my personal coding style.

**Comment by joshhting** [comment]
@eeason3 @rmkeezer thoughts? We need to achieve a 4/5 vote

**Comment by eeason3** [comment]
4 spaces, and I have no vote for the max line length.

**Comment by jgkamat** [comment]
@rmkeezer is a big spaces fan so i :cry:

**Comment by joshhting** [comment]
I will settle for spaces only if everyone prefers 4 spaces over 2. If people disagree on the number of spaces then it's pretty clear that we should be using tabs.

**Comment by jgkamat** [comment]
@strburst is still thinking about tabs/spaces, so whatever he chooses is what we'll go with
I guess we'll just go with 80 character line limit since thats 'standard'

**Comment by rmkeezer** [comment]
spaces, 80 characters

**Comment by strburst** [comment]
I would be okay with either spaces or tabs for indentation/spaces for alignment if we can stick with it. @jgkamat and @joshhting, why do you like 120 characters? I like 80 characters because then you'll be able to edit two files side-by-side easily (although I can see 113 characters in half of my extremely wide screen), and I have colorcolumn set in vim at the 81 character mark so I don't go over. It would be nice if editorconfig had an option to set colorcolumn...no wait it does! I'm so happy! I would be good with either 80 or 120 characters because I can just set colorcolumn that way.

**Comment by jgkamat** [comment]
To be honest, I'm fine with 80 character line limits too (In my opinion word wrap should be configured so  you can work with anything). We're probably going to go with 80 chars just because thats convention and we are split though...

120 lines use your whole screen (but can be word wrapped to half a screen), but 80 cannnot.

**Comment by joshhting** [comment]
Yeah I actually don't have a preference on character limit either I just went with what other people were suggesting.

**Comment by jgkamat** [comment]
Also we're using unix line endings because 3/5 unix.

**Comment by jgkamat** [comment]
We need to actually have some consensus so i'm saying
Tabs, 80 char line limits
so both parties get something they want? If a majority of people want, we can change it, but please do that as soon as possible.
