### ISSUE TITLE
Keep track of implemented extra credit

### ISSUE THREAD

**Issue by joshhting** [MountainRange/MULE#26]
We need to maintain some list to keep track of what we've done that counts for extra credit, so that at the end when they check for extra credit we won't miss out on any extra credit by accident.

**Comment by jgkamat** [comment]
We could just put it in this git repo! :smile:

**Comment by joshhting** [comment]
in the readme?

**Comment by jgkamat** [comment]
I was thinking of a seperate file, maybe extra_credit.md, but we can do whatever

**Comment by joshhting** [comment]
@MountainRange/developers thoughts guys?

**Comment by joshhting** [comment]
So far we intend to have both hotseat and simultaneous gameplay, customizable texture packs, and sound

**Comment by jgkamat** [comment]
Also, JUnits, Custom CI, Documentation Generation

**Comment by joshhting** [comment]
I'm just keeping all this in Wunderlist

**Comment by jgkamat** [comment]
Phased out by #63 I guess, closing this so discussion is in one place
