### ISSUE TITLE
Team Contract drafted

### ISSUE THREAD

**Issue by strburst** [MountainRange/MULE#3]
I finished formatting the team contract in Google Docs; you can see it [here](https://docs.google.com/document/d/1y2HX1I69CLWsZf4zPMZf6F4AUvWBk7xPJCSrJ3PxkMU/edit?usp=sharing). I also made minor clarifications here and there. Tell me if it looks good.

**Comment by joshhting** [comment]
We don't have permission to view it.

**Comment by jgkamat** [comment]
@joshhting you should have access now

**Comment by jgkamat** [comment]
Looked over it, and it LGTM. :+1:
