### ISSUE TITLE
Mysterious rectangular UFO haunts the grid at (1,1)

### ISSUE THREAD

**Issue by joshhting** [MountainRange/MULE#34]
I don't know from what hellish planet this four-sided abomination spawned from, but it must be eradicated from existence if we are to achieve a future with a perfect map.
![image](https://cloud.githubusercontent.com/assets/8889217/10345353/14a513ec-6cf7-11e5-8cec-5bd7347d15c1.png)

**Comment by joshhting** [comment]
Kill it with fire

**Comment by joshhting** [comment]
It appears these extraterrestrials have some unknown interest in grid location (1,1). The reasoning behind such preferences of four-sided beings are beyond the comprehension of three-sided beings such as us mountains.

**Comment by joshhting** [comment]
@MountainRange/peaks How should we approach this? We've never before established contact with a species with more than three sides before. Until now, such a thing would have been incomprehensible. I mean, their interior angles don't even sum up to 180 degrees. Is that even possible

**Comment by jgkamat** [comment]
Alien was politely told to leave the premises. He is still present in the codebase though, so he won't go hungry.

**Comment by joshhting** [comment]
Good. How dare they trespass on our map, infecting it with their distorted and false sense of 90 degree righteousness

**Comment by jgkamat** [comment]
Their home planet is jgkamat/ViPaint, we could launch an interrepository crusade of PR's against them...
