### ISSUE TITLE
Unrecognized junit package

### ISSUE THREAD

**Issue by joshhting** [MountainRange/MULE#39]
Do we have to build our project differently now? When I hit "Run" in IntelliJ it said "package org.junit does not exist" @jgkamat

**Comment by jgkamat** [comment]
Are you building this project with gradle? Try running `./gradlew run` from the project root

**Comment by jgkamat** [comment]
It sounds like you are using intellij to run, if so, you can set up intellij to use gradle to build instead?

**Comment by jgkamat** [comment]
Just double checked, everything should be fine...
If gradle run dosent work, try `gradle assemble`, that builds w/o tests
